### ISSUE TITLE
Any plans to make this compatible with the latest MPS version?

### ISSUE THREAD

**Issue by anthonyanjorin** [mar9000/plantmps#1]
I'm currently experimenting a bit with MPS and would love to be able to visualise my models using PlantUML.  Your project works beautifully with MPS 3.3.5 (just tried it out) but the auto-migration does not work for the latest MPS version (currently 2021.3).

Do you have any plans to migrate/upgrade this project?  I'm still too much of an MPS newbie to do this on my own.

Or has something else superseded this functionality?

Thanks,
Tony

**Comment by mar9000** [comment]
Hi, nope I do not have plans to upgrade it.

**Comment by anthonyanjorin** [comment]
OK - thanks for the quick reply.  I've now been able to get a simplified version running.  The main issue was that some methods marked as deprecated in 3.3.5 are now really gone.
